"""
SMILES → 3D PNG Rendering Pipeline
==================================
Converts SMILES strings to publication-quality 3D molecular structure images.

Workflow:
  1. RDKit: SMILES → 3D SDF (EmbedMolecule + MMFF optimization)
  2. PyMOL: SDF → High-res PNG (orthographic, ball+stick, custom colors)

Why RDKit instead of PyMOL "fetch smiles":
  PyMOL's CLI "fetch smiles=..." silently fails, producing ~16 KB blank PNGs.
  RDKit provides reliable 3D coordinate generation with MMFF force field.

Output specs (customizable):
  - Resolution: 2400 × 1800 px
  - DPI: 300
  - Bond scaling: 1.2×
  - Projection: orthographic
  - Colors: C = gray55, O = red, H = white
  - Style: ball+stick (stick_radius=0.13, sphere_scale=0.25)
"""

import os
import subprocess
import tempfile
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, List, Dict

# ── Default rendering parameters ──────────────────────────────────────────

@dataclass
class RenderConfig:
    """Configuration for 3D molecular rendering."""
    width: int = 2400
    height: int = 1800
    dpi: int = 300
    bond_scale: float = 1.2          # Bond length scaling factor
    stick_radius: float = 0.13
    sphere_scale: float = 0.25
    orthographic: bool = True
    background: str = "white"
    carbon_color: str = "gray55"
    oxygen_color: str = "red"
    hydrogen_color: str = "white"
    zoom_factor: float = 1.2


# ── SMILES → SDF (RDKit) ──────────────────────────────────────────────────

def smiles_to_sdf(
    smiles: str,
    output_path: Optional[str] = None,
    random_seed: int = 42,
    add_hydrogens: bool = True,
) -> str:
    """
    Convert a SMILES string to a 3D SDF file using RDKit.

    Steps:
      1. Parse SMILES → RDKit Mol object
      2. Add hydrogens
      3. Embed 3D coordinates (ETKDG)
      4. MMFF94 force field optimization
      5. Write SDF

    Args:
        smiles: SMILES string (e.g. 'OCc1ccc(C=O)o1' for HMF)
        output_path: Where to save the SDF. If None, uses temp file.
        random_seed: Random seed for conformer generation
        add_hydrogens: Whether to add explicit hydrogen atoms

    Returns:
        Path to the generated SDF file

    Raises:
        ValueError: If smiles is invalid
        ImportError: If RDKit is not installed
    """
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except ImportError:
        raise ImportError(
            "RDKit is required for SDF generation. "
            "Install with: pip install rdkit"
        )

    # Parse SMILES
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"RDKit could not parse SMILES: {smiles}")

    # Add hydrogens
    mol = Chem.AddHs(mol) if add_hydrogens else mol

    # Generate 3D coordinates
    params = AllChem.ETKDGv3() if hasattr(AllChem, 'ETKDGv3') else AllChem.ETKDG()
    params.randomSeed = random_seed
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        raise RuntimeError(f"Failed to embed 3D coordinates for SMILES: {smiles}")

    # MMFF optimization
    AllChem.MMFFOptimizeMolecule(mol)

    # Write SDF
    if output_path is None:
        fd, output_path = tempfile.mkstemp(suffix=".sdf", prefix="mol_")
        os.close(fd)

    writer = Chem.SDWriter(output_path)
    writer.write(mol)
    writer.close()

    return output_path


# ── SDF → PNG (PyMOL) ────────────────────────────────────────────────────

def _build_pml_script(
    sdf_path: str,
    png_path: str,
    config: RenderConfig,
) -> str:
    """Generate a PyMOL script (PML) for rendering."""
    scale = config.bond_scale
    w, h = config.width, config.height
    dpi = config.dpi

    return f"""
# Auto-generated by smiles-to-3d
reinitialize
load {sdf_path}, mol1
create mol1_scaled, mol1

hide everything, all
show sticks, mol1_scaled
show spheres, mol1_scaled

# ── Atom colors ──
color {config.carbon_color}, elem C
color {config.oxygen_color}, elem O
color {config.hydrogen_color}, elem H

# ── Style ──
set sphere_scale, {config.sphere_scale}, mol1_scaled
set stick_radius, {config.stick_radius}, mol1_scaled
set valence, 1
set depth_cue, 0
set spec_count, 0
set orthoscopic, {1 if config.orthographic else 0}
bg_color {config.background}

# ── Bond scaling (1.2×) ──
python
from pymol import cmd
obj = "mol1_scaled"
state = 1
scale = {scale}

model = cmd.get_model(obj, state)
coords = [a.coord for a in model.atom]
cx = sum(v[0] for v in coords) / len(coords)
cy = sum(v[1] for v in coords) / len(coords)
cz = sum(v[2] for v in coords) / len(coords)

cmd.alter_state(state, obj,
    "(x,y,z)=((x-cx)*scale+cx,(y-cy)*scale+cy,(z-cz)*scale+cz)",
    space={{"cx": cx, "cy": cy, "cz": cz, "scale": scale}})
cmd.rebuild()
python end

# ── Camera & render ──
orient mol1_scaled
zoom mol1_scaled, {config.zoom_factor}
png {png_path}, {w}, {h}, {dpi}, 1
quit
"""


def sdf_to_png(
    sdf_path: str,
    png_path: Optional[str] = None,
    config: Optional[RenderConfig] = None,
    pymol_bin: str = "pymol",
    workdir: Optional[str] = None,
    timeout: int = 120,
) -> str:
    """
    Render a 3D SDF file to a publication-quality PNG using PyMOL.

    Args:
        sdf_path: Path to the 3D SDF file
        png_path: Output PNG path. Defaults to sdf_path with .png extension.
        config: Rendering configuration
        pymol_bin: Path to PyMOL executable
        workdir: Working directory for PyMOL (MUST contain the SDF or use abs paths)
        timeout: Max seconds for rendering

    Returns:
        Path to the rendered PNG file

    Raises:
        FileNotFoundError: If PyMOL is not installed
        RuntimeError: If rendering fails
    """
    if not os.path.isfile(sdf_path):
        raise FileNotFoundError(f"SDF file not found: {sdf_path}")

    if config is None:
        config = RenderConfig()

    if png_path is None:
        png_path = str(Path(sdf_path).with_suffix(".png"))

    # Convert to absolute paths so PyMOL can resolve them
    sdf_abs = os.path.abspath(sdf_path)
    png_abs = os.path.abspath(png_path)

    os.makedirs(os.path.dirname(png_abs) or ".", exist_ok=True)

    # Build PML script
    pml_content = _build_pml_script(sdf_abs, png_abs, config)

    # Write PML to a temp file
    fd, pml_path = tempfile.mkstemp(suffix=".pml", prefix="render_")
    with os.fdopen(fd, 'w') as f:
        f.write(pml_content)

    try:
        result = subprocess.run(
            [pymol_bin, "-c", "-q", pml_path],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=workdir or os.path.dirname(sdf_abs),
        )

        if result.returncode != 0:
            stderr = result.stderr[:500] if result.stderr else ""
            raise RuntimeError(
                f"PyMOL rendering failed (rc={result.returncode})\n"
                f"stderr: {stderr}"
            )

    finally:
        # Clean up temp PML
        try:
            os.unlink(pml_path)
        except OSError:
            pass

    # Verification
    png_size = os.path.getsize(png_abs)
    if png_size < 50000:
        raise RuntimeError(
            f"PyMOL produced suspiciously small PNG ({png_size:,} bytes). "
            f"This usually means the SDF failed to load. "
            f"Check: (1) SDF file is valid, (2) PyMOL can read the path."
        )

    return png_abs


# ── Convenience: SMILES → PNG in one call ─────────────────────────────────

def smiles_to_png(
    smiles: str,
    output_path: Optional[str] = None,
    config: Optional[RenderConfig] = None,
    keep_sdf: bool = False,
    **kwargs,
) -> Dict[str, str]:
    """
    Convert a SMILES string directly to a 3D rendered PNG.

    This is the main convenience function combining RDKit + PyMOL.

    Args:
        smiles: SMILES string
        output_path: Output PNG path
        config: Rendering config
        keep_sdf: If True, keep the intermediate SDF file
        **kwargs: Passed to smiles_to_sdf() (e.g. random_seed, add_hydrogens)

    Returns:
        Dict with keys: 'png', 'sdf' (if keep_sdf=True)

    Example:
        >>> from smiles_to_3d import smiles_to_png
        >>> result = smiles_to_png("OCc1ccc(C=O)o1", "hmf.png")
        >>> print(result['png'])
    """
    if config is None:
        config = RenderConfig()

    # Step 1: SMILES → SDF
    sdf_path = smiles_to_sdf(smiles, **kwargs)

    # Step 2: SDF → PNG
    png_path = sdf_to_png(sdf_path, output_path, config)

    result = {"png": png_path}
    if keep_sdf:
        result["sdf"] = sdf_path
    else:
        try:
            os.unlink(sdf_path)
        except OSError:
            pass

    return result


# ── Batch rendering ──────────────────────────────────────────────────────

def batch_render(
    molecules: List[Dict[str, str]],
    output_dir: str,
    config: Optional[RenderConfig] = None,
) -> List[Dict[str, str]]:
    """
    Render multiple molecules from SMILES.

    Args:
        molecules: List of dicts with keys: 'smiles' (required), 'name' (optional)
        output_dir: Directory for output PNGs
        config: Rendering config

    Returns:
        List of result dicts with keys: 'name', 'smiles', 'png', 'sdf', 'success'

    Example:
        >>> batch_render([
        ...     {"name": "HMF", "smiles": "OCc1ccc(C=O)o1"},
        ...     {"name": "LG", "smiles": "C1[C@@H]2[C@H]([C@@H]([C@H]([C@H](O1)O2)O)O)O"},
        ... ], "./output/")
    """
    os.makedirs(output_dir, exist_ok=True)
    results = []

    for mol in molecules:
        name = mol.get("name", "molecule")
        smiles = mol["smiles"]
        png_path = os.path.join(output_dir, f"{name}.png")

        try:
            result = smiles_to_png(smiles, png_path, config, keep_sdf=False)
            results.append({
                "name": name,
                "smiles": smiles,
                "png": result["png"],
                "success": True,
            })
        except Exception as e:
            results.append({
                "name": name,
                "smiles": smiles,
                "error": str(e),
                "success": False,
            })

    return results
